version: '3'
services:
  frontend-developer:
    tty: true
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: frontend-developer
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-3000}:3000'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
    volumes:
      - './:/app'
    networks:
      - front_net

networks:
  front_net:
    driver: bridge